name: dub
version: 1.1.2
summary: Package and build manager for D applications and libraries
description: |
    DUB is a build tool for projects written in the D programming
    language, with support for automatically retrieving dependencies
    and integrating them into the build process.
confinement: classic
grade: devel

apps:
  dub:
    command: dub

parts:
  dub:
    source: https://github.com/dlang/dub.git
    source-tag: v1.1.2
    plugin: builddub
    d-compiler: ldmd2
    build-packages:
    - build-essential
    - ldc
    - libcurl4-gnutls-dev
